name: Publish Admin Plugin Artifact Package

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to publish from'
        required: false
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}  # ✅ Use manual input if provided, fallback to current branch

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          cd packages/artifact
          yarn install

      # Step 4: Generate ABIs
      - name: Generate ABIs
        run: |
          cd packages/artifact
          yarn generate

      # Step 5: Build the package
      - name: Build Package
        run: |
          cd packages/artifact
          yarn build

      # Step 6: Publish to NPM
      - name: Publish to NPM
        run: |
          cd packages/artifact
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
